=== m-bat/coins/CoVis/coins.xsd
<?xml version="1.0" encoding="utf-8"?>
<xsd:schema version="1.0" 
            xmlns="coins" targetNamespace="coins"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">

  <xsd:element name="program">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="module" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>



  <xsd:element name="module">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="function" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string" />
      <xsd:attribute name="src" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="function">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="graph" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="name" type="xsd:string"/>
      <xsd:attribute name="line" type="xsd:int"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="graph">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="node" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
      <xsd:attribute name="displayName" type="xsd:string" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="node">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="id" minOccurs="1"/>
        <xsd:element ref="next" minOccurs="0"/>
        <xsd:element ref="prev" minOccurs="0"/>
        <xsd:element ref="statement" minOccurs="1"/>
        <xsd:element ref="info" minOccurs="1"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="info">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="labelList" minOccurs="0" maxOccurs="unbounded"/>
        <xsd:element ref="stringList" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="labelList" type="labelType"/>
  <xsd:element name="stringList" type="stringType"/>


  <xsd:element name="id" type="labelType"/>
  <xsd:element name="next" type="labelType"/>
  <xsd:element name="prev" type="labelType"/>

  <xsd:element name="statement">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="hir" minOccurs="0"/>
        <xsd:element ref="lir" minOccurs="0"/>
        <xsd:element ref="hir2c" minOccurs="0"/>
        <xsd:element ref="lir2c" minOccurs="0"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="hir" type="stmtType"/>
  <xsd:element name="lir" type="stmtType"/>
  <xsd:element name="hir2c" type="stmtType"/>
  <xsd:element name="lir2c" type="stmtType"/>

  <xsd:complexType name="stmtType">
    <xsd:sequence>
      <xsd:element ref="exp" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
  </xsd:complexType>

  <xsd:element name="exp">
    <xsd:complexType>
      <xsd:simpleContent>
        <xsd:extension base="xsd:string">
          <xsd:attribute name="line" type="xsd:int"/>
        </xsd:extension>
      </xsd:simpleContent>
    </xsd:complexType>
  </xsd:element>

  <xsd:complexType name="labelType">
    <xsd:sequence>
      <xsd:element ref="elem" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="displayName" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:complexType name="stringType">
    <xsd:sequence>
      <xsd:element ref="elem" minOccurs="1" maxOccurs="unbounded"/>
    </xsd:sequence>
    <xsd:attribute name="displayName" type="xsd:string" use="required"/>
  </xsd:complexType>

  <xsd:element name="elem" type="xsd:string"/>

</xsd:schema>

=== m-bat/coins/coins-1.5-en/test/c/Sample1/fibLoop2.xml
<?xml version="1.0" encoding="utf-8"?>
<program name="coins snapsnot"
         xmlns="coins"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="coins ./coins.xsd">
  <module name="Generated HIR" src="/Users/sugimotomanabu/coins/coins-1.5-en/test/c/Sample1/fibLoop2.c">
    <function name="main" line="0">
      <graph displayName="Control Flow Graph">
        <node>
          <id displayName="_lab1">
            <elem>_lab1</elem>
          </id>
          <next displayName="Successors">
            <elem>_lab5</elem>
          </next>
          <statement>
            <hir>
              <exp>labeldSt 5 void</exp>
              <exp line="10">(assign (subs &lt;var a&gt;(conv &lt;const 0&gt;))&lt;const 1&gt;)</exp>
              <exp line="11">(assign (subs &lt;var a&gt;(conv &lt;const 1&gt;))&lt;const 1&gt;)</exp>
              <exp line="12">(assign &lt;var n&gt;&lt;const 50&gt;)</exp>
              <exp line="13">(assign &lt;var i&gt;&lt;const 2&gt;)</exp>
            </hir>
          </statement>
          <info>
            <labelList displayName="Successors">
              <elem>_lab5</elem>
            </labelList>
            <labelList displayName="Dominated Children">
              <elem>_lab5</elem>
            </labelList>
            <labelList displayName="Immediate Postdominator">
              <elem>_lab5</elem>
            </labelList>
            <stringList displayName="Live In">
              <elem>a</elem>
            </stringList>
            <stringList displayName="Live Out">
              <elem>n</elem>
              <elem>a</elem>
              <elem>i</elem>
            </stringList>
          </info>
        </node>
        <node>
          <id displayName="_lab5">
            <elem>_lab5</elem>
          </id>
          <next displayName="Successors">
            <elem>_lab6</elem>
            <elem>_lab4</elem>
          </next>
          <prev displayName="Predecessors">
            <elem>_lab1</elem>
            <elem>_lab3</elem>
          </prev>
          <statement>
            <hir>
              <exp>labeldSt 28 bool</exp>
              <exp>(expStmt (cmpLt &lt;var i&gt;&lt;var n&gt;))</exp>
            </hir>
          </statement>
          <info>
            <labelList displayName="Successors">
              <elem>_lab6</elem>
              <elem>_lab4</elem>
            </labelList>
            <labelList displayName="Predecessors">
              <elem>_lab1</elem>
              <elem>_lab3</elem>
            </labelList>
            <labelList displayName="Immediate Dominator">
              <elem>_lab1</elem>
            </labelList>
            <labelList displayName="Dominated Children">
              <elem>_lab6</elem>
              <elem>_lab4</elem>
            </labelList>
            <labelList displayName="Immediate Postdominator">
              <elem>_lab4</elem>
            </labelList>
            <labelList displayName="Postdominated Children">
              <elem>_lab1</elem>
              <elem>_lab3</elem>
            </labelList>
            <stringList displayName="Live In">
              <elem>n</elem>
              <elem>a</elem>
              <elem>i</elem>
            </stringList>
            <stringList displayName="Live Out">
              <elem>n</elem>
              <elem>a</elem>
              <elem>i</elem>
            </stringList>
          </info>
        </node>
        <node>
          <id displayName="_lab6">
            <elem>_lab6</elem>
          </id>
          <next displayName="Successors">
            <elem>_lab3</elem>
          </next>
          <prev displayName="Predecessors">
            <elem>_lab5</elem>
          </prev>
          <statement>
            <hir>
              <exp>labeldSt 35 void</exp>
              <exp line="15">(assign (subs &lt;var a&gt;(conv &lt;var i&gt;))(add (subs &lt;var a&gt;(conv (sub &lt;var i&gt;&lt;const 1&gt;)))(subs &lt;var a&gt;(conv (sub &lt;var i&gt;&lt;const 2&gt;)))))</exp>
              <exp line="16">(assign &lt;var i&gt;(add &lt;var i&gt;&lt;const 1&gt;))</exp>
            </hir>
          </statement>
          <info>
            <labelList displayName="Successors">
              <elem>_lab3</elem>
            </labelList>
            <labelList displayName="Predecessors">
              <elem>_lab5</elem>
            </labelList>
            <labelList displayName="Immediate Dominator">
              <elem>_lab5</elem>
            </labelList>
            <labelList displayName="Dominated Children">
              <elem>_lab3</elem>
            </labelList>
            <labelList displayName="Immediate Postdominator">
              <elem>_lab3</elem>
            </labelList>
            <stringList displayName="Live In">
              <elem>n</elem>
              <elem>a</elem>
              <elem>i</elem>
            </stringList>
            <stringList displayName="Live Out">
              <elem>n</elem>
              <elem>a</elem>
              <elem>i</elem>
            </stringList>
          </info>
        </node>
        <node>
          <id displayName="_lab3">
            <elem>_lab3</elem>
          </id>
          <next displayName="Successors">
            <elem>_lab5</elem>
          </next>
          <prev displayName="Predecessors">
            <elem>_lab6</elem>
          </prev>
          <statement>
            <hir>
              <exp>labeldSt 63 void</exp>
              <exp>(expStmt null)</exp>
            </hir>
          </statement>
          <info>
            <labelList displayName="Successors">
              <elem>_lab5</elem>
            </labelList>
            <labelList displayName="Predecessors">
              <elem>_lab6</elem>
            </labelList>
            <labelList displayName="Immediate Dominator">
              <elem>_lab6</elem>
            </labelList>
            <labelList displayName="Immediate Postdominator">
              <elem>_lab5</elem>
            </labelList>
            <labelList displayName="Postdominated Children">
              <elem>_lab6</elem>
            </labelList>
            <stringList displayName="Live In">
              <elem>n</elem>
              <elem>a</elem>
              <elem>i</elem>
            </stringList>
            <stringList displayName="Live Out">
              <elem>n</elem>
              <elem>a</elem>
              <elem>i</elem>
            </stringList>
          </info>
        </node>
        <node>
          <id displayName="_lab4">
            <elem>_lab4</elem>
          </id>
          <next displayName="Successors">
            <elem>_lab9</elem>
          </next>
          <prev displayName="Predecessors">
            <elem>_lab5</elem>
          </prev>
          <statement>
            <hir>
              <exp>labeldSt 67 void</exp>
              <exp>(assign &lt;var i&gt;&lt;const 2&gt;)</exp>
            </hir>
          </statement>
          <info>
            <labelList displayName="Successors">
              <elem>_lab9</elem>
            </labelList>
            <labelList displayName="Predecessors">
              <elem>_lab5</elem>
            </labelList>
            <labelList displayName="Immediate Dominator">
              <elem>_lab5</elem>
            </labelList>
            <labelList displayName="Dominated Children">
              <elem>_lab9</elem>
            </labelList>
            <labelList displayName="Immediate Postdominator">
              <elem>_lab9</elem>
            </labelList>
            <labelList displayName="Postdominated Children">
              <elem>_lab5</elem>
            </labelList>
            <stringList displayName="Live In">
              <elem>n</elem>
              <elem>a</elem>
            </stringList>
            <stringList displayName="Live Out">
              <elem>n</elem>
              <elem>a</elem>
              <elem>i</elem>
            </stringList>
          </info>
        </node>
        <node>
          <id displayName="_lab9">
            <elem>_lab9</elem>
          </id>
          <next displayName="Successors">
            <elem>_lab10</elem>
            <elem>_lab8</elem>
          </next>
          <prev displayName="Predecessors">
            <elem>_lab4</elem>
            <elem>_lab7</elem>
          </prev>
          <statement>
            <hir>
              <exp>labeldSt 75 bool</exp>
              <exp>(expStmt (cmpLt &lt;var i&gt;&lt;var n&gt;))</exp>
            </hir>
          </statement>
          <info>
            <labelList displayName="Successors">
              <elem>_lab10</elem>
              <elem>_lab8</elem>
            </labelList>
            <labelList displayName="Predecessors">
              <elem>_lab4</elem>
              <elem>_lab7</elem>
            </labelList>
            <labelList displayName="Immediate Dominator">
              <elem>_lab4</elem>
            </labelList>
            <labelList displayName="Dominated Children">
              <elem>_lab10</elem>
              <elem>_lab8</elem>
            </labelList>
            <labelList displayName="Immediate Postdominator">
              <elem>_lab8</elem>
            </labelList>
            <labelList displayName="Postdominated Children">
              <elem>_lab4</elem>
              <elem>_lab7</elem>
            </labelList>
            <stringList displayName="Live In">
              <elem>n</elem>
              <elem>a</elem>
              <elem>i</elem>
            </stringList>
            <stringList displayName="Live Out">
              <elem>n</elem>
              <elem>a</elem>
              <elem>i</elem>
            </stringList>
          </info>
        </node>
        <node>
          <id displayName="_lab10">
            <elem>_lab10</elem>
          </id>
          <next displayName="Successors">
            <elem>_lab7</elem>
          </next>
          <prev displayName="Predecessors">
            <elem>_lab9</elem>
          </prev>
